# Generated by Django 3.0.10 on 2022-08-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cfd33Formapago',
            fields=[
                ('formapagoclave', models.CharField(db_column='FORMAPAGOCLAVE', max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=80, null=True)),
            ],
        ),
    ]
