# Generated by Django 3.0.10 on 2022-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfd33Aduana',
            fields=[
                ('aduanaclave', models.CharField(db_column='ADUANACLAVE', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Claveunidadmedida',
            fields=[
                ('unidadmedidaclave', models.CharField(db_column='UNIDADMEDIDACLAVE', max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=120, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=1000, null=True)),
                ('nota', models.CharField(blank=True, db_column='NOTA', max_length=2000, null=True)),
                ('simbolo', models.CharField(blank=True, db_column='SIMBOLO', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Documentosrelacionados',
            fields=[
                ('sysid_dr', models.IntegerField(db_column='SYSID_DR', primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=99, null=True)),
                ('tipocfdi', models.CharField(db_column='TIPOCFDI', max_length=34)),
                ('consecutivo_tipocfd', models.IntegerField(db_column='CONSECUTIVO_TIPOCFD')),
                ('tiporelacion', models.CharField(blank=True, db_column='TIPORELACION', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Documentosrelacionadosfi',
            fields=[
                ('sysid_dr', models.IntegerField(db_column='SYSID_DR', primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=99, null=True)),
                ('consecutivo_tipocfd', models.IntegerField(db_column='CONSECUTIVO_TIPOCFD')),
            ],
        ),
    ]
