# Generated by Django 3.0.10 on 2022-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0002_cfd33aduana_cfd33claveunidadmedida_cfd33documentosrelacionados_cfd33documentosrelacionadosfi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfd33Impuestos',
            fields=[
                ('impuestoclave', models.CharField(db_column='IMPUESTOCLAVE', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=20, null=True)),
                ('retencion', models.CharField(blank=True, db_column='RETENCION', max_length=2, null=True)),
                ('traslado', models.CharField(blank=True, db_column='TRASLADO', max_length=2, null=True)),
                ('local', models.CharField(blank=True, db_column='LOCAL', max_length=10, null=True)),
                ('entidadaplica', models.CharField(blank=True, db_column='ENTIDADAPLICA', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Metodopago',
            fields=[
                ('metodopagoclave', models.CharField(db_column='METODOPAGOCLAVE', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Monedas',
            fields=[
                ('monedaclave', models.CharField(db_column='MONEDACLAVE', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120, null=True)),
                ('decimales', models.IntegerField(blank=True, db_column='DECIMALES', null=True)),
                ('porcentajevariacion', models.CharField(blank=True, db_column='PORCENTAJEVARIACION', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Pais',
            fields=[
                ('paisclave', models.CharField(db_column='PAISCLAVE', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Patente',
            fields=[
                ('patenteclave', models.CharField(db_column='PATENTECLAVE', max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Productosservicios',
            fields=[
                ('productoclave', models.CharField(db_column='PRODUCTOCLAVE', max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=254, null=True)),
                ('incluirivatraslado', models.CharField(blank=True, db_column='INCLUIRIVATRASLADO', max_length=20, null=True)),
                ('incluiriepstraslado', models.CharField(blank=True, db_column='INCLUIRIEPSTRASLADO', max_length=20, null=True)),
                ('complementoincluir', models.CharField(blank=True, db_column='COMPLEMENTOINCLUIR', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Regimenfiscal',
            fields=[
                ('regimenfiscalclave', models.CharField(db_column='REGIMENFISCALCLAVE', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=254, null=True)),
                ('fisica', models.CharField(blank=True, db_column='FISICA', max_length=2, null=True)),
                ('moral', models.CharField(blank=True, db_column='MORAL', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Tasacuota',
            fields=[
                ('impuesto', models.CharField(db_column='IMPUESTO', max_length=5, primary_key=True, serialize=False)),
                ('valormaximo', models.DecimalField(db_column='VALORMAXIMO', decimal_places=7, max_digits=17)),
                ('rango', models.CharField(db_column='RANGO', max_length=10)),
                ('valorminimo', models.DecimalField(blank=True, db_column='VALORMINIMO', decimal_places=6, max_digits=17, null=True)),
                ('factor', models.CharField(blank=True, db_column='FACTOR', max_length=10, null=True)),
                ('traslado', models.CharField(blank=True, db_column='TRASLADO', max_length=2, null=True)),
                ('retencion', models.CharField(blank=True, db_column='RETENCION', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Tipodecomprobante',
            fields=[
                ('tipocomprobanteclave', models.CharField(db_column='TIPOCOMPROBANTECLAVE', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Tipofactor',
            fields=[
                ('tipofactorclave', models.CharField(db_column='TIPOFACTORCLAVE', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Tiporelacion',
            fields=[
                ('tiporelacionclave', models.CharField(db_column='TIPORELACIONCLAVE', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfd33Uso',
            fields=[
                ('usoclave', models.CharField(db_column='USOCLAVE', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=120, null=True)),
                ('fisica', models.CharField(blank=True, db_column='FISICA', max_length=2, null=True)),
                ('moral', models.CharField(blank=True, db_column='MORAL', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Claveprodstcc',
            fields=[
                ('clave_stcc', models.CharField(db_column='Clave_STCC', max_length=9, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Clavetipocarga',
            fields=[
                ('clave_tipo_carga', models.CharField(db_column='Clave_Tipo_Carga', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Claveunidadpeso',
            fields=[
                ('clave_unidad', models.CharField(db_column='Clave_Unidad', max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=155)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Codigopostal',
            fields=[
                ('codigopostal', models.CharField(db_column='CODIGOPOSTAL', max_length=10, primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=3, null=True)),
                ('municipio', models.CharField(blank=True, db_column='MUNICIPIO', max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, db_column='LOCALIDAD', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Codigotransporteaereo',
            fields=[
                ('clave_identificacion', models.CharField(db_column='Clave_Identificacion', max_length=6, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(blank=True, db_column='Nacionalidad', max_length=64, null=True)),
                ('nombre_aerolinea', models.CharField(blank=True, db_column='Nombre_aerolinea', max_length=155, null=True)),
                ('oaci', models.CharField(blank=True, db_column='OACI', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Colonia',
            fields=[
                ('colonia', models.CharField(db_column='COLONIA', max_length=5, primary_key=True, serialize=False)),
                ('cp', models.CharField(db_column='CP', max_length=8)),
                ('nombre_asentamiento', models.CharField(blank=True, db_column='NOMBRE_ASENTAMIENTO', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cfdi33Configautotransporte',
            fields=[
                ('clave_nomenclatura', models.CharField(db_column='Clave_Nomenclatura', max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('numero_ejes', models.CharField(blank=True, db_column='Numero_Ejes', max_length=3, null=True)),
                ('numero_llantas', models.CharField(blank=True, db_column='Numero_llantas', max_length=25, null=True)),
            ],
        ),
    ]
