# Generated by Django 3.0.10 on 2022-08-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0003_cfd33impuestos_cfd33metodopago_cfd33monedas_cfd33pais_cfd33patente_cfd33productosservicios_cfd33regi'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cfdi33configautotransporte',
            table='CFDI33_Unidad_Medida_Aduana',
        ),
    ]
