# Generated by Django 3.0.10 on 2022-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0004_auto_20220829_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiConfigMaritima',
            fields=[
                ('clave_conf_maritima', models.CharField(db_column='Clave_Conf_Maritima', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=64, null=True)),
            ],
            options={
                'db_table': 'CFDI_ConfigMaritima',
            },
        ),
        migrations.CreateModel(
            name='CfdiContenedor',
            fields=[
                ('clave_contenedor', models.CharField(db_column='Clave_Contenedor', max_length=5, primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(blank=True, db_column='Tipo_Contenedor', max_length=4, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=155, null=True)),
            ],
            options={
                'db_table': 'CFDI_Contenedor',
            },
        ),
        migrations.CreateModel(
            name='CfdiContenedorMaritimo',
            fields=[
                ('clave_contenedor_maritimo', models.CharField(db_column='Clave_Contenedor_Maritimo', max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=65, null=True)),
            ],
            options={
                'db_table': 'CFDI_ContenedorMaritimo',
            },
        ),
        migrations.CreateModel(
            name='CfdiCveTransporteCP',
            fields=[
                ('clave_transporte', models.CharField(db_column='Clave_Transporte', max_length=2, primary_key=True, serialize=False)),
                ('descripcion_transporte', models.CharField(blank=True, db_column='Descripcion_Transporte', max_length=25, null=True)),
            ],
            options={
                'db_table': 'CFDI_CveTransporteCP',
            },
        ),
        migrations.CreateModel(
            name='CfdiDerechosDePaso',
            fields=[
                ('clave_derecho_peso', models.CharField(db_column='Clave_Derecho_Peso', max_length=7, primary_key=True, serialize=False)),
                ('derecho_peso', models.CharField(blank=True, db_column='Derecho_peso', max_length=7, null=True)),
                ('entre', models.CharField(blank=True, db_column='Entre', max_length=155, null=True)),
                ('hasta', models.CharField(blank=True, db_column='Hasta', max_length=155, null=True)),
                ('otorga_recibe', models.CharField(blank=True, db_column='Otorga_Recibe', max_length=55, null=True)),
                ('concesionario', models.CharField(blank=True, db_column='Concesionario', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CFDI_DerechosDePaso',
            },
        ),
        migrations.CreateModel(
            name='CfdiEstados',
            fields=[
                ('estado', models.CharField(db_column='ESTADO', max_length=4, primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='NOMBRE_ESTADO', max_length=64, null=True)),
            ],
            options={
                'db_table': 'CFDI_Estados',
            },
        ),
        migrations.CreateModel(
            name='CfdiExportacion',
            fields=[
                ('id_clave', models.CharField(db_column='ID_CLAVE', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=19, null=True)),
            ],
            options={
                'db_table': 'CFDI_Exportacion',
            },
        ),
        migrations.CreateModel(
            name='CfdiFraccion',
            fields=[
                ('fraccionarencelaria', models.CharField(db_column='FRACCIONARENCELARIA', max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
                ('um', models.CharField(blank=True, db_column='UM', max_length=4, null=True)),
                ('imp', models.CharField(blank=True, db_column='IMP', max_length=19, null=True)),
                ('exp', models.CharField(blank=True, db_column='EXP', max_length=4, null=True)),
            ],
            options={
                'db_table': 'CFDI_Fraccion',
            },
        ),
        migrations.CreateModel(
            name='CfdiMaterialPeligroso',
            fields=[
                ('clave_material_peligroso', models.CharField(db_column='Clave_Material_Peligroso', max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=1000, null=True)),
                ('clase_div', models.CharField(blank=True, db_column='Clase_div', max_length=55, null=True)),
                ('peligro_secundario', models.CharField(blank=True, db_column='Peligro_Secundario', max_length=55, null=True)),
                ('emb_env_onu', models.CharField(blank=True, db_column='EMB_ENV_ONU', max_length=55, null=True)),
                ('disp_espec', models.CharField(blank=True, db_column='Disp_Espec', max_length=55, null=True)),
                ('cant_limitadas', models.CharField(blank=True, db_column='Cant_Limitadas', max_length=55, null=True)),
                ('exceptuadas', models.CharField(blank=True, db_column='Exceptuadas', max_length=55, null=True)),
                ('inst_emb_env', models.CharField(blank=True, db_column='Inst_EMB_ENV', max_length=55, null=True)),
                ('disp_espec_emba_env', models.CharField(blank=True, db_column='Disp_Espec_Emba_ENV', max_length=55, null=True)),
                ('cisternasport_inst_transp', models.CharField(blank=True, db_column='CisternasPort_Inst_transp', max_length=55, null=True)),
                ('rig_disp_espec', models.CharField(blank=True, db_column='RIG_Disp_Espec', max_length=55, null=True)),
            ],
            options={
                'db_table': 'CFDI_MaterialPeligroso',
            },
        ),
        migrations.CreateModel(
            name='CfdiMeses',
            fields=[
                ('id_clave', models.CharField(db_column='ID_CLAVE', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=49, null=True)),
            ],
            options={
                'db_table': 'CFDI_Meses',
            },
        ),
        migrations.CreateModel(
            name='CfdiMotivoCancelacion',
            fields=[
                ('id_cancelacion', models.CharField(db_column='ID_CANCELACION', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=249, null=True)),
            ],
            options={
                'db_table': 'CFDI_Motivo_Cancelacion',
            },
        ),
        migrations.CreateModel(
            name='CfdiMotivoTraslado',
            fields=[
                ('motivo_traslado', models.CharField(db_column='MOTIVO_TRASLADO', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=64, null=True)),
            ],
            options={
                'db_table': 'CFDI_MOTIVO_TRASLADO',
            },
        ),
        migrations.CreateModel(
            name='CfdiNumautorizacionnaviero',
            fields=[
                ('numero_autorizacion', models.CharField(db_column='Numero_Autorizacion', max_length=20, primary_key=True, serialize=False)),
                ('inicio_vigencia', models.IntegerField(blank=True, db_column='Inicio_Vigencia', null=True)),
                ('inicio_vigencia_field', models.CharField(blank=True, db_column='Inicio_Vigencia_', max_length=9, null=True)),
                ('fin_vigencia', models.IntegerField(blank=True, db_column='Fin_Vigencia', null=True)),
                ('fin_vigencia_field', models.CharField(blank=True, db_column='Fin_Vigencia_', max_length=9, null=True)),
            ],
            options={
                'db_table': 'CFDI_NumAutorizacionNaviero',
            },
        ),
        migrations.CreateModel(
            name='CfdiObjetoimp',
            fields=[
                ('id_clave', models.CharField(db_column='ID_CLAVE', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=49, null=True)),
            ],
            options={
                'db_table': 'CFDI_ObjetoImp',
            },
        ),
        migrations.CreateModel(
            name='CfdiPeriodicidad',
            fields=[
                ('id_clave', models.CharField(db_column='ID_CLAVE', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=14, null=True)),
            ],
            options={
                'db_table': 'CFDI_Periodicidad',
            },
        ),
        migrations.CreateModel(
            name='CfdiRemolques',
            fields=[
                ('sysid_remolque', models.IntegerField(db_column='SYSID_REMOLQUE', primary_key=True, serialize=False)),
                ('rem1_subtipo', models.CharField(blank=True, db_column='REM1_SUBTIPO', max_length=7, null=True)),
                ('rem1_placa', models.CharField(blank=True, db_column='REM1_PLACA', max_length=7, null=True)),
            ],
            options={
                'db_table': 'CFDI_Remolques',
            },
        ),
        migrations.CreateModel(
            name='CfdiSubtiporem',
            fields=[
                ('clave_remolque', models.CharField(db_column='Clave_Remolque', max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CFDI_SubTipoRem',
            },
        ),
        migrations.CreateModel(
            name='CfdiTipoCarro',
            fields=[
                ('clave_tipocarro', models.CharField(db_column='Clave_TipoCarro', max_length=5, primary_key=True, serialize=False)),
                ('tipo_carro', models.CharField(blank=True, db_column='Tipo_Carro', max_length=25, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=155, null=True)),
            ],
            options={
                'db_table': 'CFDI_TipoCarro',
            },
        ),
        migrations.CreateModel(
            name='CfdiTipodeservicio',
            fields=[
                ('clave_tiposervicio', models.CharField(db_column='Clave_TipoServicio', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=55)),
            ],
            options={
                'db_table': 'CFDI_TipoDeServicio',
            },
        ),
        migrations.CreateModel(
            name='CfdiTipoembalaje',
            fields=[
                ('clave_designacion', models.CharField(db_column='Clave_Designacion', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CFDI_TipoEmbalaje',
            },
        ),
        migrations.CreateModel(
            name='CfdiTipoEstacion',
            fields=[
                ('clave_estacion', models.CharField(db_column='Clave_Estacion', max_length=2, primary_key=True, serialize=False)),
                ('descripcion_tipo_estacion', models.CharField(blank=True, db_column='Descripcion_Tipo_Estacion', max_length=25, null=True)),
                ('clave_transporte', models.CharField(blank=True, db_column='Clave_Transporte', max_length=19, null=True)),
            ],
            options={
                'db_table': 'CFDI_TipoEstacion',
            },
        ),
        migrations.CreateModel(
            name='CfdiTipopermiso',
            fields=[
                ('clave', models.CharField(db_column='Clave', max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('clave_transporte', models.CharField(blank=True, db_column='Clave_Transporte', max_length=2, null=True)),
            ],
            options={
                'db_table': 'CFDI_TipoPermiso',
            },
        ),
        migrations.CreateModel(
            name='CfdiUnidadMedidaAduana',
            fields=[
                ('unidad_medida_aduana', models.IntegerField(db_column='UNIDAD_MEDIDA_ADUANA', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=54, null=True)),
            ],
            options={
                'db_table': 'CFDI_Unidad_Medida_Aduana',
            },
        ),
        migrations.RenameModel(
            old_name='Cfd33Aduana',
            new_name='CfdiAduana',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Claveprodstcc',
            new_name='CfdiClaveprodSTCC',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Clavetipocarga',
            new_name='CfdiClavetipoCarga',
        ),
        migrations.RenameModel(
            old_name='Cfd33Claveunidadmedida',
            new_name='CfdiClaveUnidadMedida',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Claveunidadpeso',
            new_name='CfdiClaveUnidadPeso',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Codigopostal',
            new_name='CfdiCodigoPostal',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Codigotransporteaereo',
            new_name='CfdiCodigoTransporteAereo',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Colonia',
            new_name='CfdiColonia',
        ),
        migrations.RenameModel(
            old_name='Cfdi33Configautotransporte',
            new_name='CfdiConfigAutoTransporte',
        ),
        migrations.RenameModel(
            old_name='Cfd33Documentosrelacionados',
            new_name='CfdiDocumentosRelacionados',
        ),
        migrations.RenameModel(
            old_name='Cfd33Documentosrelacionadosfi',
            new_name='CfdiDocumentosRelacionadosFI',
        ),
        migrations.RenameModel(
            old_name='Cfd33Formapago',
            new_name='CfdiFormaPago',
        ),
        migrations.RenameModel(
            old_name='Cfd33Impuestos',
            new_name='CfdiImpuestos',
        ),
        migrations.RenameModel(
            old_name='Cfd33Metodopago',
            new_name='CfdiMetodoPago',
        ),
        migrations.RenameModel(
            old_name='Cfd33Monedas',
            new_name='CfdiMonedas',
        ),
        migrations.RenameModel(
            old_name='Cfd33Pais',
            new_name='CfdiPais',
        ),
        migrations.RenameModel(
            old_name='Cfd33Patente',
            new_name='CfdiPatente',
        ),
        migrations.RenameModel(
            old_name='Cfd33Productosservicios',
            new_name='CfdiProductosServicios',
        ),
        migrations.RenameModel(
            old_name='Cfd33Regimenfiscal',
            new_name='CfdiRegimenFiscal',
        ),
        migrations.RenameModel(
            old_name='Cfd33Tasacuota',
            new_name='CfdiTasaCuota',
        ),
        migrations.RenameModel(
            old_name='Cfd33Tipodecomprobante',
            new_name='CfdiTipoDeComprobante',
        ),
        migrations.RenameModel(
            old_name='Cfd33Tipofactor',
            new_name='CfdiTipoFactor',
        ),
        migrations.RenameModel(
            old_name='Cfd33Tiporelacion',
            new_name='CfdiTipoRelacion',
        ),
        migrations.RenameModel(
            old_name='Cfd33Uso',
            new_name='CfdiUso',
        ),
        migrations.AlterModelTable(
            name='cfdiaduana',
            table='CFDI_Aduana',
        ),
        migrations.AlterModelTable(
            name='cfdiclaveprodstcc',
            table='CFDI_ClaveprodSTCC',
        ),
        migrations.AlterModelTable(
            name='cfdiclavetipocarga',
            table='CFDI_ClavetipoCarga',
        ),
        migrations.AlterModelTable(
            name='cfdiclaveunidadmedida',
            table='CFDI_ClaveUnidadMedida',
        ),
        migrations.AlterModelTable(
            name='cfdiclaveunidadpeso',
            table='CFDI_ClaveUnidadPeso',
        ),
        migrations.AlterModelTable(
            name='cfdicodigopostal',
            table='CFDI_CodigoPostal',
        ),
        migrations.AlterModelTable(
            name='cfdicodigotransporteaereo',
            table='CFDI_CodigoTransporteAereo',
        ),
        migrations.AlterModelTable(
            name='cfdicolonia',
            table='CFDI_Colonia',
        ),
        migrations.AlterModelTable(
            name='cfdiconfigautotransporte',
            table='CFDI_ConfigAutoTransporte',
        ),
        migrations.AlterModelTable(
            name='cfdidocumentosrelacionados',
            table='CFDI_DocumentosRelacionados',
        ),
        migrations.AlterModelTable(
            name='cfdidocumentosrelacionadosfi',
            table='CFDI_DocumentosRelacionadosFI',
        ),
        migrations.AlterModelTable(
            name='cfdiformapago',
            table='CFDI_Formapago',
        ),
        migrations.AlterModelTable(
            name='cfdiimpuestos',
            table='CFDI_Impuestos',
        ),
        migrations.AlterModelTable(
            name='cfdimetodopago',
            table='CFDI_Metodopago',
        ),
        migrations.AlterModelTable(
            name='cfdimonedas',
            table='CFDI_Monedas',
        ),
        migrations.AlterModelTable(
            name='cfdipais',
            table='CFDI_Pais',
        ),
        migrations.AlterModelTable(
            name='cfdipatente',
            table='CFDI_Patente',
        ),
        migrations.AlterModelTable(
            name='cfdiproductosservicios',
            table='CFDI_ProductosServicios',
        ),
        migrations.AlterModelTable(
            name='cfdiregimenfiscal',
            table='CFDI_RegimenFiscal',
        ),
        migrations.AlterModelTable(
            name='cfditasacuota',
            table='CFDI_Tasacuota',
        ),
        migrations.AlterModelTable(
            name='cfditipodecomprobante',
            table='CFDI_TipoDeComprobante',
        ),
        migrations.AlterModelTable(
            name='cfditipofactor',
            table='CFDI_TipoFactor',
        ),
        migrations.AlterModelTable(
            name='cfditiporelacion',
            table='CFDI_TipoRelacion',
        ),
        migrations.AlterModelTable(
            name='cfdiuso',
            table='CFDI_Uso',
        ),
        migrations.CreateModel(
            name='CfdiMunicipios',
            fields=[
                ('municipio', models.CharField(db_column='MUNICIPIO', max_length=4, primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='ESTADO', max_length=4)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=149, null=True)),
            ],
            options={
                'db_table': 'CFDI_Municipios',
                'unique_together': {('municipio', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='CfdiLocalidades',
            fields=[
                ('localidades', models.CharField(db_column='LOCALIDADES', max_length=3, primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='ESTADO', max_length=4)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=150, null=True)),
            ],
            options={
                'db_table': 'CFDI_Localidades',
                'unique_together': {('localidades', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='CfdiEstaciones',
            fields=[
                ('clave_transporte', models.CharField(db_column='Clave_Transporte', max_length=2, primary_key=True, serialize=False)),
                ('clave_identificacion', models.CharField(db_column='Clave_Identificacion', max_length=6)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=65, null=True)),
                ('nacionalidad', models.CharField(blank=True, db_column='Nacionalidad', max_length=35, null=True)),
                ('iata', models.CharField(blank=True, db_column='IATA', max_length=4, null=True)),
                ('linea_ferrea', models.CharField(blank=True, db_column='Linea_Ferrea', max_length=9, null=True)),
            ],
            options={
                'db_table': 'CFDI_Estaciones',
                'unique_together': {('clave_transporte', 'clave_identificacion')},
            },
        ),
    ]
