# Generated by Django 3.0.10 on 2022-12-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssconf',
            name='backColor',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
