# Generated by Django 3.0.10 on 2022-12-07 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Config', '0003_auto_20221204_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssconf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_confCSS', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
