# Generated by Django 3.0.10 on 2022-12-07 00:41

import Profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0004_cssconf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssconf',
            name='fondo',
            field=models.ImageField(upload_to=Profiles.models.user_avatar_directory_path),
        ),
    ]
