# Generated by Django 3.0.10 on 2022-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_auto_20221206_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssconf',
            name='fontColor',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='cssconf',
            name='backColor',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
