# Generated by Django 3.0.10 on 2022-10-26 02:18

import Profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(default='avatar.png', upload_to=Profiles.models.user_avatar_directory_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(blank=True, max_length=55, null=True)),
                ('good_at_bio', models.TextField(blank=True)),
                ('mywork_bio', models.TextField(blank=True)),
                ('contact_msn', models.TextField(blank=True)),
                ('show_socials', models.BooleanField(default=True)),
                ('show_ReadMore', models.BooleanField(default=True)),
                ('show_GoodAt', models.BooleanField(default=True)),
                ('show_WorkImages', models.BooleanField(default=True)),
                ('follows', models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='Profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technology_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=55, unique=True)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='profilie_social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin')], max_length=30)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_social', to='Profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='profileReadeMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('section_type', models.CharField(choices=[('ReadMore', 'Read More'), ('GoodAt', 'Good At')], default='ReadMore', max_length=10)),
                ('left_rigth', models.CharField(choices=[('right', 'image to right'), ('left', 'image to left')], default='left', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileRM', to='Profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='profile_work_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=25)),
                ('data_type', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=65)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_works', to='Profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_contactuser', to='Profiles.Profile')),
            ],
        ),
    ]
