# Generated by Django 3.0.10 on 2022-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_work_images',
            name='data_type',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
