# Generated by Django 3.0.10 on 2022-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='Profiles.Profile'),
        ),
    ]
