# Generated by Django 3.0.10 on 2022-11-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=55, unique=True)),
                ('desc', models.TextField(max_length=150)),
            ],
            options={
                'ordering': ['tech'],
            },
        ),
    ]
