# Generated by Django 3.0.10 on 2022-10-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20221003_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileReadeMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('ReadMore', 'Read More'), ('GoodAt', 'Good At')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='profile_work_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=25)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_readmore', to='Profiles.profileReadeMore')),
            ],
        ),
    ]
