# Generated by Django 3.0.10 on 2022-11-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20221106_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontact',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
