# Generated by Django 3.0.10 on 2022-11-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_technology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_work_images',
            name='data_type',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
