# Generated by Django 3.0.10 on 2022-11-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_customcontact_is_readed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcontact',
            options={'ordering': ['is_readed', '-created']},
        ),
    ]
