# Generated by Django 3.0.10 on 2022-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_profile_work_images_profilereademore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereademore',
            name='description',
            field=models.TextField(),
        ),
    ]
