# Generated by Django 3.0.10 on 2022-11-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20221106_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_work_images',
            name='data_type',
            field=models.CharField(choices=[('Python', 'Python-super language')], max_length=30),
        ),
        migrations.AlterField(
            model_name='technology_type',
            name='desc',
            field=models.TextField(max_length=150),
        ),
    ]
