# Generated by Django 3.0.10 on 2022-10-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20221011_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_work_images',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_works', to='Profiles.Profile'),
        ),
    ]
