# Generated by Django 3.0.10 on 2022-11-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_auto_20221109_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilie_social_media',
            options={'ordering': ['social_type']},
        ),
    ]
