# Generated by Django 3.0.10 on 2022-10-13 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_profile_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereademore',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileRM', to='Profiles.Profile'),
        ),
    ]
