# Generated by Django 3.0.10 on 2022-10-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_auto_20221012_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=55)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='profile_work_images',
            name='data_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
