# Generated by Django 3.0.10 on 2022-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0009_auto_20221015_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_work_images',
            name='desc',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='profile_work_images',
            name='data_type',
            field=models.CharField(choices=[('Python', 'Python-Python 3.10'), ('Javascript', 'Javascript-Javascript ECMA6')], max_length=30),
        ),
    ]
