# Generated by Django 3.0.10 on 2022-10-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0011_profilie_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilie_social_media',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
