# Generated by Django 3.0.10 on 2022-10-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_profilie_social_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilie_social_media',
            name='url',
            field=models.URLField(blank=True, default='#', max_length=255, null=True),
        ),
    ]
