# Generated by Django 3.0.10 on 2022-10-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0013_auto_20221019_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilie_social_media',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
