# Generated by Django 3.0.10 on 2022-10-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0014_auto_20221019_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='good_at_bio',
            field=models.TextField(blank=True),
        ),
    ]
