# Generated by Django 3.0.10 on 2022-10-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0016_profile_mywork_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology_type',
            name='tech',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
