# Generated by Django 3.0.10 on 2022-10-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0017_auto_20221023_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_GoodAt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_ReadMore',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_WorkImages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_socials',
            field=models.BooleanField(default=True),
        ),
    ]
