# Generated by Django 3.0.10 on 2022-10-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0018_auto_20221023_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_msn',
            field=models.TextField(blank=True),
        ),
    ]
